# 共通設定
spring:
  application:
    name: todoapp
  jpa:
    open-in-view: false
  profiles:
    active: dev

server:
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: never
    whitelabel:
      enabled: false

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"
