# 開発環境用設定
spring:
  datasource:
    url: jdbc:h2:file:./data/test_db;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        '[format_sql]': true
  h2:
    console:
      enabled: true
      path: /h2-console
  devtools:
    restart:
      enabled: true

logging:
  level:
    root: DEBUG
    '[com.example.todoapp]': DEBUG

app:
  cors:
    allowed-origins:
      - "http://localhost:5173"
